<a href="https://colab.research.google.com/github/Priyaboomikannu/AIRLINE_DATABASE-/blob/main/1_pandas_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#Part 1 – Dataset Understanding
#1.	Import the Pandas library and load the dataset.

import pandas as pd
df=pd.read_csv("/content/uncleaned_airline_dataset_20_columns.csv")
df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.0,NaN,Non-Veg,30kg,Not Checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.0,Non-Refundable,NONE,unknown,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,NaN,Non-Refundable,Non-Veg,25,checked,terminal-2,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.0,NaN,NaN,30kg,NaN,terminal-2,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.0,NaN,NONE,unknown,checked-in,T3,NaN,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265,2.0,Non-Refundable,NaN,25,NaN,T3,0,C101
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105,1.0,NON REFUNDABLE,Non-Veg,15,Checked-In,T1,15,C104
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099,NaN,NON REFUNDABLE,NONE,NaN,NaN,NaN,unknown,C103
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585,4.0,Non-Refundable,Non-Veg,15,NaN,terminal-2,5,C104
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585,2.0,NON REFUNDABLE,veg,25,NaN,NaN,unknown,C104

In [2]:
#2.	Display the first 10 rows of the dataset.
df.head(10)

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.0,NaN,Non-Veg,30kg,Not Checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.0,Non-Refundable,NONE,unknown,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,NaN,Non-Refundable,Non-Veg,25,checked,terminal-2,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.0,NaN,NaN,30kg,NaN,terminal-2,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.0,NaN,NONE,unknown,checked-in,T3,NaN,C101
5,5,Vistara,UK-945,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.33,1,5955,4.0,refundable,NaN,15,Checked-In,T2,0,C103
6,6,Vistara,UK-927,Delhi,Morning,zero,Morning,Mumbai,Economy,2.08,1,6060,4.0,refundable,veg,30kg,Not Checked,T2,5,C101
7,7,Vistara,UK-951,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.17,1,6060,4.0,NON REFUNDABLE,NONE,15,Not Checked,T2,NaN,NaN
8,8,GO_FIRST,G8-334,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.17,1,5954,2.0,refundable,Veg,unknown,checked-in,T1,15,C104
9,9,GO_FIRST,G8-336,Delhi,Afternoon,zero,Evening,Mumbai,Economy,2.25,1,5954,4.0,NON REFUNDABLE,Non-Veg,25,Not Checked,T1,unknown,C104

In [3]:
# 3.	Display the last 10 rows of the dataset.
df.tail(10)

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
300143,300143,Air_India,AI-440,Chennai,Early_Morning,one,Night,Hyderabad,Business,17.42,49,51345,NaN,NaN,NONE,25,Checked-In,T1,30,NaN
300144,300144,Air_India,AI-539,Chennai,Evening,one,Morning,Hyderabad,Business,18.92,49,51345,5.0,Non-Refundable,Veg,unknown,Not Checked,Terminal 1,unknown,C105
300145,300145,Air_India,AI-430,Chennai,Morning,one,Morning,Hyderabad,Business,23.08,49,51345,4.0,NON REFUNDABLE,veg,20,checked-in,Terminal 1,60,C105
300146,300146,Air_India,AI-440,Chennai,Early_Morning,one,Morning,Hyderabad,Business,26.83,49,51345,4.0,NON REFUNDABLE,veg,30kg,checked-in,T3,10,NaN
300147,300147,Air_India,AI-569,Chennai,Early_Morning,one,Night,Hyderabad,Business,17.25,49,68739,3.0,Refundable,veg,25,Checked-In,terminal-2,10,C104
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265,2.0,Non-Refundable,NaN,25,NaN,T3,0,C101
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105,1.0,NON REFUNDABLE,Non-Veg,15,Checked-In,T1,15,C104
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099,NaN,NON REFUNDABLE,NONE,NaN,NaN,NaN,unknown,C103
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585,4.0,Non-Refundable,Non-Veg,15,NaN,terminal-2,5,C104
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585,2.0,NON REFUNDABLE,veg,25,NaN,NaN,unknown,C104

In [4]:
#4.	Find the total number of rows and columns in the dataset.
df.shape

(300153, 20)

In [5]:
#5.	Display the list of all column names.
df.columns

Index(['index', 'airline', 'flight', 'source_city', 'departure_time', 'stops',
       'arrival_time', 'destination_city', 'class', 'duration', 'days_left',
       'price', 'Passenger_Rating', 'Ticket_Type', 'Meal_Option', 'Baggage_kg',
       'Checkin_Status', 'Airport_Terminal', 'Delay_Minutes', 'Customer_ID'],
      dtype='object')

In [6]:
#Part 2 – Dataset Inspection
#6.	Display the data types of all columns.
df.dtypes

index                 int64
airline              object
flight               object
source_city          object
departure_time       object
stops                object
arrival_time         object
destination_city     object
class                object
duration            float64
days_left             int64
price                 int64
Passenger_Rating    float64
Ticket_Type          object
Meal_Option          object
Baggage_kg           object
Checkin_Status       object
Airport_Terminal     object
Delay_Minutes        object
Customer_ID          object
dtype: object

In [7]:
# 7.	Display basic statistical summary of the dataset.
df.describe()

,index,duration,days_left,price,Passenger_Rating
count,300153.000000,300153.000000,300153.000000,300153.000000,224988.000000
mean,150076.000000,12.221021,26.004751,20889.660523,3.172458
std,86646.852011,7.191997,13.561004,22697.767366,1.342857
min,0.000000,0.830000,1.000000,1105.000000,1.000000
25%,75038.000000,6.830000,15.000000,4783.000000,2.000000
50%,150076.000000,11.250000,26.000000,7425.000000,4.000000
75%,225114.000000,16.170000,38.000000,42521.000000,4.000000
max,300152.000000,49.830000,49.000000,123071.000000,5.000000

In [8]:
# 8. Identify which columns contain missing values.
df.isnull().any()

index               False
airline             False
flight              False
source_city         False
departure_time      False
stops               False
arrival_time        False
destination_city    False
class               False
duration            False
days_left           False
price               False
Passenger_Rating     True
Ticket_Type          True
Meal_Option          True
Baggage_kg           True
Checkin_Status       True
Airport_Terminal     True
Delay_Minutes        True
Customer_ID          True
dtype: bool

In [9]:
#9.	Count the number of missing values in each column.
df.isnull().sum()

index                   0
airline                 0
flight                  0
source_city             0
departure_time          0
stops                   0
arrival_time            0
destination_city        0
class                   0
duration                0
days_left               0
price                   0
Passenger_Rating    75165
Ticket_Type         60296
Meal_Option         59825
Baggage_kg          49689
Checkin_Status      59611
Airport_Terminal    49931
Delay_Minutes       37682
Customer_ID         49627
dtype: int64

In [10]:
#10.	Display the number of unique values in each column.
df.nunique()

index               300153
airline                  6
flight                1561
source_city              6
departure_time           6
stops                    3
arrival_time             6
destination_city         6
class                    2
duration               476
days_left               49
price                12157
Passenger_Rating         5
Ticket_Type              4
Meal_Option              4
Baggage_kg               5
Checkin_Status           4
Airport_Terminal         5
Delay_Minutes            7
Customer_ID              5
dtype: int64

In [11]:
#Part 3 – Data Cleaning (Missing Values)
#11.	Replace missing values in Passenger_Rating with the mean value.
df['Passenger_Rating'].fillna(df['Passenger_Rating'].mean(),inplace=True)
df

/tmp/ipykernel_439/4232200576.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Passenger_Rating'].fillna(df['Passenger_Rating'].mean(),inplace=True)

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.000000,NaN,Non-Veg,30kg,Not Checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.000000,Non-Refundable,NONE,unknown,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,3.172458,Non-Refundable,Non-Veg,25,checked,terminal-2,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.000000,NaN,NaN,30kg,NaN,terminal-2,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.000000,NaN,NONE,unknown,checked-in,T3,NaN,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265,2.000000,Non-Refundable,NaN,25,NaN,T3,0,C101
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105,1.000000,NON REFUNDABLE,Non-Veg,15,Checked-In,T1,15,C104
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099,3.172458,NON REFUNDABLE,NONE,NaN,NaN,NaN,unknown,C103
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585,4.000000,Non-Refundable,Non-Veg,15,NaN,terminal-2,5,C104
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585,2.000000,NON REFUNDABLE,veg,25,NaN,NaN,unknown,C104

In [12]:
#12.	Replace missing values in Meal_Option with "Unknown".
df['Meal_Option'].fillna("Unknown",inplace=True)
df

/tmp/ipykernel_439/115137514.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Meal_Option'].fillna("Unknown",inplace=True)

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.000000,NaN,Non-Veg,30kg,Not Checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.000000,Non-Refundable,NONE,unknown,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,3.172458,Non-Refundable,Non-Veg,25,checked,terminal-2,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.000000,NaN,Unknown,30kg,NaN,terminal-2,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.000000,NaN,NONE,unknown,checked-in,T3,NaN,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265,2.000000,Non-Refundable,Unknown,25,NaN,T3,0,C101
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105,1.000000,NON REFUNDABLE,Non-Veg,15,Checked-In,T1,15,C104
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099,3.172458,NON REFUNDABLE,NONE,NaN,NaN,NaN,unknown,C103
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585,4.000000,Non-Refundable,Non-Veg,15,NaN,terminal-2,5,C104
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585,2.000000,NON REFUNDABLE,veg,25,NaN,NaN,unknown,C104

In [13]:
import numpy as np

In [14]:
#13.	Replace missing values in Baggage_kg with the median value.

df['Baggage_kg'].replace({"30kg":30,"25":25,"15":15},inplace=True)

/tmp/ipykernel_439/835817370.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Baggage_kg'].replace({"30kg":30,"25":25,"15":15},inplace=True)

In [15]:
df['Baggage_kg'].replace("unknown",np.nan,inplace=True)

In [16]:
df['Baggage_kg'].fillna(df['Baggage_kg'].median(),inplace=True)

In [17]:
#14.	Remove rows where Customer_ID is missing.
df.dropna(subset=['Customer_ID'],inplace=True)
df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.000000,NaN,Non-Veg,30,Not Checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.000000,Non-Refundable,NONE,20.0,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,3.172458,Non-Refundable,Non-Veg,25,checked,terminal-2,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.000000,NaN,Unknown,30,NaN,terminal-2,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.000000,NaN,NONE,20.0,checked-in,T3,NaN,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265,2.000000,Non-Refundable,Unknown,25,NaN,T3,0,C101
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105,1.000000,NON REFUNDABLE,Non-Veg,15,Checked-In,T1,15,C104
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099,3.172458,NON REFUNDABLE,NONE,20.0,NaN,NaN,unknown,C103
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585,4.000000,Non-Refundable,Non-Veg,15,NaN,terminal-2,5,C104
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585,2.000000,NON REFUNDABLE,veg,25,NaN,NaN,unknown,C104

In [18]:
#15.	Verify that missing values are handled.
df.isnull().any()

index               False
airline             False
flight              False
source_city         False
departure_time      False
stops               False
arrival_time        False
destination_city    False
class               False
duration            False
days_left           False
price               False
Passenger_Rating    False
Ticket_Type          True
Meal_Option         False
Baggage_kg          False
Checkin_Status       True
Airport_Terminal     True
Delay_Minutes        True
Customer_ID         False
dtype: bool

In [19]:
#Part 4 – String Cleaning
#16.	Remove leading and trailing spaces from all string columns.
df.columns.str.strip()

Index(['index', 'airline', 'flight', 'source_city', 'departure_time', 'stops',
       'arrival_time', 'destination_city', 'class', 'duration', 'days_left',
       'price', 'Passenger_Rating', 'Ticket_Type', 'Meal_Option', 'Baggage_kg',
       'Checkin_Status', 'Airport_Terminal', 'Delay_Minutes', 'Customer_ID'],
      dtype='object')

In [20]:
#17.	Convert Meal_Option values to lowercase.
df['Meal_Option']=df['Meal_Option'].str.lower()
df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.000000,NaN,non-veg,30,Not Checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.000000,Non-Refundable,none,20.0,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,3.172458,Non-Refundable,non-veg,25,checked,terminal-2,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.000000,NaN,unknown,30,NaN,terminal-2,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.000000,NaN,none,20.0,checked-in,T3,NaN,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265,2.000000,Non-Refundable,unknown,25,NaN,T3,0,C101
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105,1.000000,NON REFUNDABLE,non-veg,15,Checked-In,T1,15,C104
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099,3.172458,NON REFUNDABLE,none,20.0,NaN,NaN,unknown,C103
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585,4.000000,Non-Refundable,non-veg,15,NaN,terminal-2,5,C104
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585,2.000000,NON REFUNDABLE,veg,25,NaN,NaN,unknown,C104

In [21]:
df["Ticket_Type"].unique()

array([nan, 'Non-Refundable', ' refundable ', 'NON REFUNDABLE',
       'Refundable'], dtype=object)

In [22]:
#18.	Convert Ticket_Type values to proper format (Refundable / Non-Refundable).
df['Ticket_Type'] = df['Ticket_Type'].replace({
    'NON REFUNDABLE':'Non-Refundable',
    'refundable':'Refundable',
    ' refundable ':'Refundable'
})

In [23]:
df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.000000,NaN,non-veg,30,Not Checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.000000,Non-Refundable,none,20.0,checked-in,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,3.172458,Non-Refundable,non-veg,25,checked,terminal-2,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.000000,NaN,unknown,30,NaN,terminal-2,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.000000,NaN,none,20.0,checked-in,T3,NaN,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265,2.000000,Non-Refundable,unknown,25,NaN,T3,0,C101
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105,1.000000,Non-Refundable,non-veg,15,Checked-In,T1,15,C104
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099,3.172458,Non-Refundable,none,20.0,NaN,NaN,unknown,C103
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585,4.000000,Non-Refundable,non-veg,15,NaN,terminal-2,5,C104
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585,2.000000,Non-Refundable,veg,25,NaN,NaN,unknown,C104

In [24]:
#19.	Standardize Checkin_Status values.
df["Checkin_Status"].unique()

array(['Not Checked', 'checked-in', '  checked ', nan, 'Checked-In'],
      dtype=object)

In [25]:
df['Checkin_Status'] = df['Checkin_Status'].replace({
    'checked-in':"Checked", '  checked ':"Checked", 'Checked-In':"Checked"
})

In [26]:
df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.000000,NaN,non-veg,30,Not Checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.000000,Non-Refundable,none,20.0,Checked,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,3.172458,Non-Refundable,non-veg,25,Checked,terminal-2,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.000000,NaN,unknown,30,NaN,terminal-2,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.000000,NaN,none,20.0,Checked,T3,NaN,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265,2.000000,Non-Refundable,unknown,25,NaN,T3,0,C101
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105,1.000000,Non-Refundable,non-veg,15,Checked,T1,15,C104
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099,3.172458,Non-Refundable,none,20.0,NaN,NaN,unknown,C103
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585,4.000000,Non-Refundable,non-veg,15,NaN,terminal-2,5,C104
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585,2.000000,Non-Refundable,veg,25,NaN,NaN,unknown,C104

In [27]:
#20.	Standardize Airport_Terminal values to T1, T2, T3 format.
df["Airport_Terminal"].unique()

array(['T2', nan, 'terminal-2', 'T3', 'T1', 'Terminal 1'], dtype=object)

In [28]:
df['Airport_Terminal'] = df['Airport_Terminal'].replace({
    'terminal-2':"T1","Terminal 1":"T1"
})

In [29]:
df

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.000000,NaN,non-veg,30,Not Checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.000000,Non-Refundable,none,20.0,Checked,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,3.172458,Non-Refundable,non-veg,25,Checked,T1,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.000000,NaN,unknown,30,NaN,T1,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.000000,NaN,none,20.0,Checked,T3,NaN,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265,2.000000,Non-Refundable,unknown,25,NaN,T3,0,C101
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105,1.000000,Non-Refundable,non-veg,15,Checked,T1,15,C104
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099,3.172458,Non-Refundable,none,20.0,NaN,NaN,unknown,C103
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585,4.000000,Non-Refundable,non-veg,15,NaN,T1,5,C104
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585,2.000000,Non-Refundable,veg,25,NaN,NaN,unknown,C104

In [30]:
df['Passenger_Rating'].fillna(df['Passenger_Rating'].mean(),inplace=True)
df

/tmp/ipykernel_439/4265854534.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Passenger_Rating'].fillna(df['Passenger_Rating'].mean(),inplace=True)

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.000000,NaN,non-veg,30,Not Checked,T2,30,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.000000,Non-Refundable,none,20.0,Checked,NaN,10,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,3.172458,Non-Refundable,non-veg,25,Checked,T1,unknown,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.000000,NaN,unknown,30,NaN,T1,unknown,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.000000,NaN,none,20.0,Checked,T3,NaN,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265,2.000000,Non-Refundable,unknown,25,NaN,T3,0,C101
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105,1.000000,Non-Refundable,non-veg,15,Checked,T1,15,C104
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099,3.172458,Non-Refundable,none,20.0,NaN,NaN,unknown,C103
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585,4.000000,Non-Refundable,non-veg,15,NaN,T1,5,C104
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585,2.000000,Non-Refundable,veg,25,NaN,NaN,unknown,C104

In [31]:
#Part 5 – Data Type Cleaning (5 Questions)
#21.	Convert Passenger_Rating column to numeric datatype.
df['Passenger_Rating'].astype(int)

0         5
1         4
2         3
3         1
4         4
         ..
300148    2
300149    1
300150    3
300151    4
300152    2
Name: Passenger_Rating, Length: 250526, dtype: int64

In [42]:
# 22.	Convert Baggage_kg values by removing "kg" text.
df["Delay_Minutes"].unique()

array([30., 10., nan,  0.,  5., 15., 60.])

In [44]:
df["Delay_Minutes"].replace({"30":30,"10":10," 15 ":15,"5":5,"60":60,"0":0},inplace=True)

In [45]:

#24.	Replace "unknown" values with NaN.
df['Delay_Minutes'].replace('unknown',np.nan,inplace=True)

In [46]:
df["Baggage_kg"].fillna(df["Baggage_kg"].median(),inplace=True)

/tmp/ipykernel_439/3981878639.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["Baggage_kg"].fillna(df["Baggage_kg"].median(),inplace=True)

In [52]:
df['Delay_Minutes'].fillna(df['Delay_Minutes'].median(),inplace=True)

In [53]:
#23.	Convert Delay_Minutes column into integer datatype.
df['Delay_Minutes'].astype(int)

0         30
1         10
2         10
3         10
4         10
          ..
300148     0
300149    15
300150    10
300151     5
300152    10
Name: Delay_Minutes, Length: 250526, dtype: int64

In [54]:
#25.	Verify the updated data types.
print(df.dtypes)

index                 int64
airline              object
flight               object
source_city          object
departure_time       object
stops                object
arrival_time         object
destination_city     object
class                object
duration            float64
days_left             int64
price                 int64
Passenger_Rating    float64
Ticket_Type          object
Meal_Option          object
Baggage_kg           object
Checkin_Status       object
Airport_Terminal     object
Delay_Minutes       float64
Customer_ID          object
dtype: object

In [55]:
#part 6 - Duplicate Data Handling
#26.	Check whether duplicate rows exist in the dataset.
df.duplicated().any()

np.False_

In [56]:
#27.	Count the number of duplicate rows.
df.duplicated().sum()

np.int64(0)

In [57]:
#28.	Remove duplicate rows from the dataset.
df.drop_duplicates()

,index,airline,flight,source_city,departure_time,stops,arrival_time,destination_city,class,duration,days_left,price,Passenger_Rating,Ticket_Type,Meal_Option,Baggage_kg,Checkin_Status,Airport_Terminal,Delay_Minutes,Customer_ID
0,0,SpiceJet,SG-8709,Delhi,Evening,zero,Night,Mumbai,Economy,2.17,1,5953,5.000000,NaN,non-veg,30,Not Checked,T2,30.0,C101
1,1,SpiceJet,SG-8157,Delhi,Early_Morning,zero,Morning,Mumbai,Economy,2.33,1,5953,4.000000,Non-Refundable,none,20.0,Checked,NaN,10.0,C103
2,2,AirAsia,I5-764,Delhi,Early_Morning,zero,Early_Morning,Mumbai,Economy,2.17,1,5956,3.172458,Non-Refundable,non-veg,25,Checked,T1,10.0,C105
3,3,Vistara,UK-995,Delhi,Morning,zero,Afternoon,Mumbai,Economy,2.25,1,5955,1.000000,NaN,unknown,30,NaN,T1,10.0,C102
4,4,Vistara,UK-963,Delhi,Morning,zero,Morning,Mumbai,Economy,2.33,1,5955,4.000000,NaN,none,20.0,Checked,T3,10.0,C101
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
300148,300148,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,69265,2.000000,Non-Refundable,unknown,25,NaN,T3,0.0,C101
300149,300149,Vistara,UK-826,Chennai,Afternoon,one,Night,Hyderabad,Business,10.42,49,77105,1.000000,Non-Refundable,non-veg,15,Checked,T1,15.0,C104
300150,300150,Vistara,UK-832,Chennai,Early_Morning,one,Night,Hyderabad,Business,13.83,49,79099,3.172458,Non-Refundable,none,20.0,NaN,NaN,10.0,C103
300151,300151,Vistara,UK-828,Chennai,Early_Morning,one,Evening,Hyderabad,Business,10.00,49,81585,4.000000,Non-Refundable,non-veg,15,NaN,T1,5.0,C104
300152,300152,Vistara,UK-822,Chennai,Morning,one,Evening,Hyderabad,Business,10.08,49,81585,2.000000,Non-Refundable,veg,25,NaN,NaN,10.0,C104

In [58]:
# part 7 - Basic Data Analysis
#29.	Find the total number of flights in the dataset.
df['flight'].count()

np.int64(250526)

In [59]:
#30.	Find the number of unique airlines.
df['airline'].unique()

array(['SpiceJet', 'AirAsia', 'Vistara', 'GO_FIRST', 'Indigo',
       'Air_India'], dtype=object)

In [60]:
#31.	Display the list of unique source cities.
df['source_city'].unique()

array(['Delhi', 'Mumbai', 'Bangalore', 'Kolkata', 'Hyderabad', 'Chennai'],
      dtype=object)

In [61]:
#32.	Display the list of unique destination cities.
df['destination_city'].unique()

array(['Mumbai', 'Bangalore', 'Kolkata', 'Hyderabad', 'Chennai', 'Delhi'],
      dtype=object)

In [62]:
#33.	Count flights for each airline.
df.groupby('airline')['flight'].count()

airline
AirAsia       13402
Air_India     67465
GO_FIRST      19368
Indigo        36105
SpiceJet       7530
Vistara      106656
Name: flight, dtype: int64

In [63]:
# part 8 - Price Analysis
#34.	Find the average ticket price.
df.groupby('Ticket_Type')['price'].mean()

Ticket_Type
Non-Refundable    20835.275917
Refundable        20896.328991
Name: price, dtype: float64

In [64]:
#35.	Find the maximum ticket price.
df.groupby('Ticket_Type')['price'].max()

Ticket_Type
Non-Refundable    117307
Refundable        116562
Name: price, dtype: int64

In [65]:
#36.	Find the minimum ticket price.
df.groupby('Ticket_Type')['price'].min()

Ticket_Type
Non-Refundable    1105
Refundable        1105
Name: price, dtype: int64

In [66]:
#36.	Find the minimum ticket price.
df.groupby('airline')['price'].min()

airline
AirAsia      1105
Air_India    1526
GO_FIRST     1105
Indigo       1105
SpiceJet     1106
Vistara      1714
Name: price, dtype: int64

In [67]:
df['flight'].unique()

array(['SG-8709', 'SG-8157', 'I5-764', ..., '6E-7259', 'AI-433', 'AI-652'],
      dtype=object)

In [68]:
#38.	Display the top 5 most expensive flights.
df.groupby('flight')['price'].nlargest(5)

flight
0.00E+00  97174       8832
          100735      7220
          97470       6092
          98232       5178
          98608       5178
                     ...
UK-996    230092    114523
          241548    111964
          241599    111964
          230088    105764
          230089    105764
Name: price, Length: 7509, dtype: int64

In [69]:
# part 9 - City Analysis
#39.	Find the number of flights from each source city.
df.groupby('source_city')['flight'].count()

source_city
Bangalore    43400
Chennai      32321
Delhi        51252
Hyderabad    33995
Kolkata      38765
Mumbai       50793
Name: flight, dtype: int64

In [70]:
#40.	Find the number of flights to each destination city.
df.groupby('destination_city')['flight'].count()

destination_city
Bangalore    42789
Chennai      33733
Delhi        47760
Hyderabad    35641
Kolkata      41396
Mumbai       49207
Name: flight, dtype: int64

In [71]:
#41.	Identify the source city with the most flights.
df.groupby('source_city')['flight'].max()

source_city
Bangalore    UK-897
Chennai      UK-838
Delhi        UK-995
Hyderabad    UK-898
Kolkata      UK-778
Mumbai       UK-996
Name: flight, dtype: object

In [72]:
#42.	Find the average ticket price for each source city.
df.groupby('source_city')['price'].min()

source_city
Bangalore    1603
Chennai      1105
Delhi        1998
Hyderabad    1543
Kolkata      2436
Mumbai       1890
Name: price, dtype: int64

In [73]:
# part 10 - Flight Details Analysis
#43.	Count flights based on number of stops.
df.groupby('flight')['price'].min()

flight
0.00E+00     2201
6.00E-102    1755
6.00E-105    4079
6.00E-113    2201
6.00E-121    1543
             ...
UK-988       2339
UK-993       2700
UK-994       2339
UK-995       2700
UK-996       2339
Name: price, Length: 1555, dtype: int64

In [74]:
#44.	Find the average price based on flight class.
df.groupby('flight')['stops'].count()

flight
0.00E+00       42
6.00E-102      33
6.00E-105       5
6.00E-113      37
6.00E-121      19
             ...
UK-988       1133
UK-993        738
UK-994       1064
UK-995        836
UK-996       1070
Name: stops, Length: 1555, dtype: int64

In [75]:
#45.	Find the airline with the highest average passenger rating.
df.groupby('airline')['Passenger_Rating'].mean().max()

3.1834009845158606

In [76]:
#46.	Count flights based on departure time.
df.groupby('flight')['departure_time'].count()

flight
0.00E+00       42
6.00E-102      33
6.00E-105       5
6.00E-113      37
6.00E-121      19
             ...
UK-988       1133
UK-993        738
UK-994       1064
UK-995        836
UK-996       1070
Name: departure_time, Length: 1555, dtype: int64

In [77]:
# part 11 - Delay Analysis
#47.	Find the average delay minutes of flights.

df.groupby('flight')['Delay_Minutes'].count()

flight
0.00E+00       42
6.00E-102      33
6.00E-105       5
6.00E-113      37
6.00E-121      19
             ...
UK-988       1133
UK-993        738
UK-994       1064
UK-995        836
UK-996       1070
Name: Delay_Minutes, Length: 1555, dtype: int64

In [79]:
#48.	Display flights delayed more than 30 minutes.
df.loc[df['Delay_Minutes'] > 30, ['flight']]

         flight
12      6E-5001
28      SG-8169
33       UK-817
34       UK-819
37       AI-453
...         ...
300100   UK-838
300106   UK-834
300136   UK-834
300142   AI-539
300145   AI-430

[31318 rows x 1 columns]

In [80]:
#Part 12 – Final Output (2 Questions)
#50.	Display the final shape of the cleaned dataset.
df.shape

(250526, 20)

In [86]:
df.isnull().any()

index               False
airline             False
flight              False
source_city         False
departure_time      False
stops               False
arrival_time        False
destination_city    False
class               False
duration            False
days_left           False
price               False
Passenger_Rating    False
Ticket_Type         False
Meal_Option         False
Baggage_kg          False
Checkin_Status      False
Airport_Terminal    False
Delay_Minutes       False
Customer_ID         False
dtype: bool

In [83]:
df['Ticket_Type'].fillna("unknown",inplace=True)

/tmp/ipykernel_439/4000707178.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Ticket_Type'].fillna("unknown",inplace=True)

In [84]:
df['Checkin_Status'].fillna("unknown",inplace=True)

/tmp/ipykernel_439/4060902272.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Checkin_Status'].fillna("unknown",inplace=True)

In [85]:
df['Airport_Terminal'].fillna("unknown",inplace=True)

/tmp/ipykernel_439/2455131230.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['Airport_Terminal'].fillna("unknown",inplace=True)